### ISSUE TITLE
Is it an open project?

### ISSUE THREAD

**Issue by kination** [Stanford-Mobisocial-IoT-Lab/thingengine-platform-android#22]
Hello~
I just visited your repo, and looks interesting. But while building android project, I saw issue like below.

```
Error:Execution failed for task ':app:buildJsDebug'.
> Process 'command './build_js.sh'' finished with non-zero exit value 127
```

When I run build_js.sh on terminal, I see `Missing destination directory` on line. How can I fix it?
Also, if this is an open project for every user, how about making installation guide?

Thanks.

**Comment by sileix** [comment]
Hi djKooks, 

Thanks for your interest in our project. For your questions:
1. Exit value 127 returned by sh means the command is not found in PATH, it's probably caused by node or/and npm is not installed.  
2. This project is an open project, but it's still in its early stage, changes are made on daily basis. We will have the installation guide soon and will be more than happy if you would like to contribute. 
Feel free to contact us for further questions. 

Best regards,
Silei.

**Comment by kination** [comment]
@rayslxu thanks!
1. Exit value 127 returned by sh means the command is not found in PATH, it's probably caused by node or/and npm is not installed.
   -> I run this script on terminal, where node / npm is already installed, but returned `Missing destination directory`. Do I have to setup some directory for this?
2. This project is an open project, but it's still in its early stage, changes are made on daily basis. We will have the installation guide soon and will be more than happy if you would like to contribute. 
   -> That's good. Thanks!

**Comment by sileix** [comment]
@djKooks 

I believe I had the same problem when I was working on this on a Mac. For some reason the PATH used in the script is not the same with the environment variable on your mac. Try add line "echo $PATH" at the beginning of build_js.sh and see if it is the problem. If so, add "PATH=$PATH:YOUR_PATH_TO_NPM" and "export PATH" at the beginning. Hope it will work. 

If you want to run script from terminal, run "./build_js.sh ." (with a dot at the end). But when you build the app via android studio, it will run the script again, so that not gonna help anyway.

**Comment by kination** [comment]
@rayslxu Sorry, it still doesn't work after I setup the PATH for `npm`.
This is the detail gradle log for this.

```
+ test -d ../node_modules/babel-cli
+ transpile_js
+ ../node_modules/.bin/babel --preset es2015 --ignore 'jsapp/node_modules/*/test/*' -D -d ./src/main/assets/jxcore ../jsapp/
env: node: No such file or directory

:app:buildJsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJsDebug'.
> Process 'command './build_js.sh'' finished with non-zero exit value 127
```

I add this code on top of `build_js.sh`

```
PATH=$PATH:"/usr/local/lib/node_modules/npm"
export PATH
```

Could you find something wrong?
Thanks

**Comment by sileix** [comment]
I just checked my build_js.sh file on my Mac, in which I added "export PATH=/usr/local/bin:$Path" at the beginning. And by deleting this line, I am able to reproduce the same error. Hope this will help you solve the problem.

Actually, maybe we can add this line to the repository directly if it works.

**Comment by gcampax** [comment]
You have npm in your path but not node. You need both commands.

**Comment by kination** [comment]
@rayslxu @gcampax Okay, there was some progress.
I added `export PATH=/usr/local/bin:$PATH` on script, and run `npm install` at terminal on jsapp directory. Now it went more far, but still have some issue.

```
...
../jsapp/node_modules/lokijs/benchmark/benchmark_pouchdb.js -> src/main/assets/jxcore/node_modules/lokijs/benchmark/benchmark_pouchdb.js
../jsapp/node_modules/lokijs/benchmark/benchmark_web.js -> src/main/assets/jxcore/node_modules/lokijs/benchmark/benchmark_web.js

SyntaxError: ../jsapp/node_modules/lokijs/benchmark/nedb.js: Octal literal in strict mode (232:14)
  230 | 
  231 |     if (style) {
> 232 |       return '\033[' + styles[style][0] + 'm' + str +
      |               ^
  233 |              '\033[' + styles[style][1] + 'm';
  234 |     } else {
  235 |       return str;

:app:buildJsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJsDebug'.
> Process 'command './build_js.sh'' finished with non-zero exit value 1
...
```

Could you look on this one?

**Comment by gcampax** [comment]
Do not run npm install in jsapp/ :)
If you did already, "git clean -fdx" inside it.

npm will be run automatically by build_js at the right time, that is, after running babel. If you run it before, babel will transpile the dependency in addition to our code, and as you can see that fails miserably.

**Comment by kination** [comment]
@gcampax got it. Now I cleaned my local project with 'git clean -fdx' and run, but still causing error.

```
:app:buildJsDebug
+ test -d ../node_modules/babel-cli
+ transpile_js
+ ../node_modules/.bin/babel --preset es2015 --ignore 'jsapp/node_modules/*/test/*' -D -d ./src/main/assets/jxcore ../jsapp/

../jsapp/app.js -> src/main/assets/jxcore/app.js
../jsapp/assistant.js -> src/main/assets/jxcore/assistant.js
../jsapp/config.js -> src/main/assets/jxcore/config.js
../jsapp/control.js -> src/main/assets/jxcore/control.js
../jsapp/graphics.js -> src/main/assets/jxcore/graphics.js
../jsapp/java_api.js -> src/main/assets/jxcore/java_api.js
../jsapp/json_datagram_socket.js -> src/main/assets/jxcore/json_datagram_socket.js
../jsapp/node_modules/leveldown/chained-batch.js -> src/main/assets/jxcore/node_modules/leveldown/chained-batch.js
../jsapp/node_modules/leveldown/iterator.js -> src/main/assets/jxcore/node_modules/leveldown/iterator.js
../jsapp/node_modules/leveldown/leveldown.js -> src/main/assets/jxcore/node_modules/leveldown/leveldown.js
../jsapp/platform.js -> src/main/assets/jxcore/platform.js
../jsapp/streams.js -> src/main/assets/jxcore/streams.js
../jsapp/util/feeds.js -> src/main/assets/jxcore/util/feeds.js

+ install_deps
+ cd ./src/main/assets/jxcore/
+ npm install --no-optional --only=prod --no-bin-links
+ cd ./src/main/assets/jxcore/node_modules/thingengine-core
./build_js.sh: line 42: cd: ./src/main/assets/jxcore/node_modules/thingengine-core: No such file or directory

:app:buildJsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJsDebug'.
> Process 'command './build_js.sh'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Also, I have node and npm both on /usr/local/bin

```
...
lrwxr-xr-x    1 dennis  admin      36 18 Apr 13:59 mongotop -> ../Cellar/mongodb/3.2.4/bin/mongotop
lrwxr-xr-x    1 dennis  admin      29 25 Mar  2016 node -> ../Cellar/node/5.7.0/bin/node
lrwxr-xr-x    1 dennis  admin      36 15 Set 16:11 nodetool -> ../Cellar/cassandra/3.5/bin/nodetool
lrwxr-xr-x    1 dennis  staff      67 30 Set 09:29 notary -> /Users/kwangin/Library/Group Containers/group.com.docker/bin/notary
lrwxr-xr-x    1 dennis  admin      46 25 Mar  2016 npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
lrwxr-xr-x    1 dennis  admin      39  9 Ago 15:23 oid2name -> ../Cellar/postgresql/9.5.2/bin/oid2name
lrwxr-xr-x    1 dennis  admin      35 23 Giu 15:16 pal2rgb -> ../Cellar/libtiff/4.0.6/bin/pal2rgb
...
```

**Comment by sileix** [comment]
@djKooks 
It seems like you didn't update the submodules. Try "git submodule update --init --recursive" before building.

**Comment by kination** [comment]
@rayslxu Thanks for support. It has some change, but it still cause failure.

I tried these commands, and opened android studio.

```
$ git clean -fdx
$ git checkout .
$ git submodule update --init --recursive
error: no such remote ref 61a71a476399043368a4076add5cdb102c5dcf8f
Fetched in submodule path 'jxcore', but it did not contain 61a71a476399043368a4076add5cdb102c5dcf8f. Direct fetching of that commit failed.
```

And below has caused when open android studio again.

```
npm WARN thingengine-core@1.0.0 No repository field.
npm WARN thingengine-core@1.0.0 No license field.
+ npm run compile-mo

> thingengine-core@1.0.0 compile-mo /Users/kwangin/workspace/github_source/thingengine-platform-android/app/src/main/assets/jxcore/node_modules/thingengine-core
> for i in po/*.po ; do msgfmt $i -o po/`basename $i .po`.mo ; done


sh: msgfmt: command not found
sh: msgfmt: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "run" "compile-mo"
npm ERR! node v5.7.0
npm ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! thingengine-core@1.0.0 compile-mo: `for i in po/*.po ; do msgfmt $i -o po/`basename $i .po`.mo ; done`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the thingengine-core@1.0.0 compile-mo script 'for i in po/*.po ; do msgfmt $i -o po/`basename $i .po`.mo ; done'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the thingengine-core package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     for i in po/*.po ; do msgfmt $i -o po/`basename $i .po`.mo ; done
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs thingengine-core
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls thingengine-core
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kwangin/workspace/github_source/thingengine-platform-android/app/src/main/assets/jxcore/node_modules/thingengine-core/npm-debug.log

:app:buildJsDebug FAILED

FAILURE: Build failed with an exception.
```

Hope you could find something.

**Comment by gcampax** [comment]
You also need to install the gettext tools (msgfmt, msgmerge, xgettext). I don't know what package provides them on OS X, they are called gettext or gettext-bin on Linux. Homebrew probably has packages for it.

**Comment by kination** [comment]
There were some progress, but not cleared yet.

```
../jsapp/node_modules/thingtalk/lib/grammar.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/grammar.js
../jsapp/node_modules/thingtalk/lib/input_compiler.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/input_compiler.js
../jsapp/node_modules/thingtalk/lib/internal.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/internal.js
../jsapp/node_modules/thingtalk/lib/output_compiler.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/output_compiler.js
../jsapp/node_modules/thingtalk/lib/schema.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/schema.js
../jsapp/node_modules/thingtalk/lib/type.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/type.js
../jsapp/node_modules/thingtalk/lib/type_check.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/type_check.js
../jsapp/node_modules/thingtalk/lib/utils.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/utils.js
../jsapp/node_modules/thingtalk/lib/visitor.js -> src/main/assets/jxcore/node_modules/thingtalk/lib/visitor.js
../jsapp/platform.js -> src/main/assets/jxcore/platform.js
../jsapp/streams.js -> src/main/assets/jxcore/streams.js
../jsapp/util/feeds.js -> src/main/assets/jxcore/util/feeds.js

+ install_deps
+ cd ./src/main/assets/jxcore/
+ npm install --no-optional --only=prod --no-bin-links

- abstract-leveldown@2.4.1 node_modules/thingengine-core/node_modules/abstract-leveldown
thingengine-android@1.0.0 /Users/kwangin/workspace/github_source/thingengine-platform-android/app/src/main/assets/jxcore
`-- (empty)


npm ERR! code 1

:app:buildJsDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:buildJsDebug'.
> Process 'command './build_js.sh'' finished with non-zero exit value 1
```

Looks like something is missing on 'jxcore'. Is it related with this error when I called submodules?

```
$ git submodule update --init --recursive
error: no such remote ref 61a71a476399043368a4076add5cdb102c5dcf8f
Fetched in submodule path 'jxcore', but it did not contain 61a71a476399043368a4076add5cdb102c5dcf8f. Direct fetching of that commit failed.
```

And one more, I am testing with removing some gradle source lines that are related with key values because it cannot find keystore file. It looks like not related with this.

```
...
    def keystoreProperties = new Properties()
    //keystoreProperties.load(new FileInputStream(rootProject.file("keystore.properties")))
    signingConfigs {
        release {
/*
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
*/
        }
    }
```

Thanks for help.

**Comment by gcampax** [comment]
Nah, the error is unrelated to submodules (it's a different folder).
I've seen that error occasionally since I moved from node 4.\* to node 6.*. It happens sporadically. Try building again and it will probably work.

**Comment by kination** [comment]
@gcampax Okay. I tried again after remove -> reinstall node to newest version(6.7.0).
I still got a same issue, but find out some way to solve it. 

I removed `( cd "${jxcoredir}/" ; npm install debug --no-optional --only=prod --no-bin-links )` on `build_js.sh` file and re-builded with Android Studio. This has worked.

I'm not sure this is the correct way, because app installed well after this but caused error like I mentioned below. Could you look on?

```
10-05 10:53:36.040 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: Error: connect ECONNREFUSED
10-05 10:53:36.040 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: $c@net.js:837:7
                                                                           $09@net.js:829:13
10-05 10:53:36.048 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: Error: socket hang up -1
10-05 10:53:36.048 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: $0n@http.js:1101:8
                                                                           $0W@http.js:1150:18
                                                                           $q@events.js:82:1
                                                                           emit@events.js:169:1
                                                                           $f.prototype._destroy/<@net.js:422:1
10-05 10:53:36.232 5691-5714/edu.stanford.thingengine.engine E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                                               Process: edu.stanford.thingengine.engine, PID: 5691
                                                                               java.lang.RuntimeException: connect ECONNREFUSED

                                                                                   at io.jxcore.node.JXMobile$1.Receiver(JXMobile.java:39)
                                                                                   at io.jxcore.node.jxcore.javaCall(jxcore.java:158)
                                                                                   at io.jxcore.node.jxcore.loop(Native Method)
                                                                                   at io.jxcore.node.jxcore.Loop(jxcore.java:132)
                                                                                   at edu.stanford.thingengine.engine.service.EngineThread.run(EngineThread.java:81)
```

Is this error related with what I mentioned, or just some access problem?

**Comment by djKooks** [comment]
Also, after installing app, I faced on error like this.
```
10-05 10:53:36.040 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: Error: connect ECONNREFUSED
10-05 10:53:36.040 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: $c@net.js:837:7
                                                                           $09@net.js:829:13
10-05 10:53:36.048 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: Error: socket hang up -1
10-05 10:53:36.048 5691-5714/edu.stanford.thingengine.engine E/jxcore-log: $0n@http.js:1101:8
                                                                           $0W@http.js:1150:18
                                                                           $q@events.js:82:1
                                                                           emit@events.js:169:1
                                                                           $f.prototype._destroy/<@net.js:422:1
10-05 10:53:36.232 5691-5714/edu.stanford.thingengine.engine E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                                               Process: edu.stanford.thingengine.engine, PID: 5691
                                                                               java.lang.RuntimeException: connect ECONNREFUSED
                                                                               
                                                                                   at io.jxcore.node.JXMobile$1.Receiver(JXMobile.java:39)
                                                                                   at io.jxcore.node.jxcore.javaCall(jxcore.java:158)
                                                                                   at io.jxcore.node.jxcore.loop(Native Method)
                                                                                   at io.jxcore.node.jxcore.Loop(jxcore.java:132)
                                                                                   at edu.stanford.thingengine.engine.service.EngineThread.run(EngineThread.java:81)
```
Looks like there are connection refuse. Is there a permission or something to access?
Thanks.

**Comment by gcampax** [comment]
It's definitely a different error.
Can you ping sabrina-nl.stanford.edu and thingengine.stanford.edu from your emulator? It might just be a network issue.

**Comment by kination** [comment]
@gcampax `thingengine.stanford.edu` seem not connectable here.

```
$ ping thingengine.stanford.edu
PING thingengine-front-1333079886.us-west-2.elb.amazonaws.com (52.25.233.229): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5
Request timeout for icmp_seq 6
Request timeout for icmp_seq 7
Request timeout for icmp_seq 8
Request timeout for icmp_seq 9
```

Is this an issue?

**Comment by gcampax** [comment]
pings are dropped by Amazon's firewall in front of the website. Try connecting to it with a browser instead.

**Comment by kination** [comment]
@gcampax Oh you're right. It connects fine on my browser. Could you figure out the problem on app?

**Comment by gcampax** [comment]
Most likely a configuration issue in the emulator. Check if you can open the website in a mobile browser.

**Comment by kination** [comment]
@gcampax Yes, it access well on my mobile browser(chrome on nexus 6p).
And one more, I cannot access to `sabrina-nl.stanford.edu` on my browser, though ping works well. It shows '404 not found' in safari browser. Maybe this could be a problem.

**Comment by gcampax** [comment]
sabrina-nl.stanford.edu only responds to /query (/query?q=whatever)
If you get a 404 it's not a connection refused error.

And yeah, it's a weird issue that you get this error.
We have a nexus 6p here and we've tested the app, it works here...

Can you try the build at https://rink.hockeyapp.net/apps/d6e09574c0f9434e8e20e8d8f2234285 ?

**Comment by kination** [comment]
Oh, this works well. It's quite strange. Is this can be related with keystore issue I commented before(I removed keystore process on gradle because there are no related files)?

Also, though I success to build apk on my local pc, it shows some error on gradle.

```
Information:Gradle tasks [:app:assembleDebug]
Error:+-- readable-stream@1.0.34
Error:`-- xtend@2.1.2
Error:`-- object-keys@0.4.0
Error:+-- end-of-stream@1.1.0
Error:| `-- once@1.3.3
Error:`-- once@1.4.0
Error:`-- wrappy@1.0.2
Error:+-- core-util-is@1.0.2
Error:+-- isarray@0.0.1
Error:`-- string_decoder@0.10.31
Error:+-- fastfall@1.5.1
Error:+-- fastparallel@2.3.0
Error:+-- fastq@1.4.1
Error:+-- fastseries@1.7.2
Error:`-- reusify@1.0.1
Error:`-- errno@0.1.4
Error:`-- prr@0.0.0
Error:`-- ms@0.7.1
Information:BUILD SUCCESSFUL
Information:Total time: 57.601 secs
Information:18 errors
Information:0 warnings
Information:See complete output in console
```

Is this appears same on your side too?

**Comment by gcampax** [comment]
I don't think the keystore matters, if you make a debug build of the app. And yeah those messages appear to be spurious, probably your version of npm is logging on stderr instead of stdout.

**Comment by kination** [comment]
Thanks. Is there some other part that could cause this kind of network error?

**Comment by kination** [comment]
@gcampax It is quite strange that now it is working well. Was there some change on server? Anyway, thanks for support. I'll keep follow up about this, and let you know if problem occurs again.

Thanks.

**Comment by gcampax** [comment]
Well closing the issue for now
